using Momentum.Audio;
using UnityEngine;

namespace Momentum.Levels
{
    /// <summary>
    /// Describes one campaign level: its scene, display data, rank times and music.
    /// Generated by the setup tool (ScriptableObjects/Levels) and listed in the LevelRegistry.
    /// </summary>
    [CreateAssetMenu(menuName = "Momentum/Level Definition", fileName = "LevelDefinition")]
    public class LevelDefinition : ScriptableObject
    {
        [Tooltip("Stable id used by the save file. Do not change after release.")]
        public string id = "level01";
        public int number = 1;
        public string displayName = "Training Facility";
        [Tooltip("Scene name as listed in Build Settings.")]
        public string sceneName = "Level01_TrainingFacility";
        [TextArea(2, 5)]
        public string description = "";

        [Header("Boss")]
        public bool isBossLevel;
        public string bossName = "";

        [Header("Presentation")]
        public Color accentColor = new Color(1f, 0.45f, 0.1f);
        public MusicTrack music = MusicTrack.Level;

        [Header("Time Trial")]
        [Tooltip("Times (seconds) required for each rank. Anything slower than C is D.")]
        public RankThresholds rankTimes = RankThresholds.Default;

        public string DisplayNumber => number.ToString("00");
    }
}
