using System;
using System.Collections.Generic;
using UnityEngine;

namespace Momentum
{
    /// <summary>
    /// Named material palette generated by the setup tool. Level objects reference materials by key
    /// (for example "White", "Accent", "Glass") so custom JSON levels stay small and readable.
    /// </summary>
    [CreateAssetMenu(menuName = "Momentum/Material Library", fileName = "MaterialLibrary")]
    public class MaterialLibrary : ScriptableObject
    {
        [Serializable]
        public class Entry
        {
            public string key;
            public Material material;
        }

        /// <summary>Material keys selectable in the level editor for geometry.</summary>
        public static readonly string[] GeometryKeys =
        {
            "White", "LightGray", "Gray", "Dark", "Accent", "AccentBlue", "AccentRed", "AccentGreen", "AccentYellow", "Hazard", "Glass"
        };

        public static readonly string[] SkyboxKeys = { "Day", "Dusk", "Night", "Boss" };

        public List<Entry> materials = new List<Entry>();
        public List<Entry> skyboxes = new List<Entry>();

        [Header("Special materials")]
        public Material editorGrid;
        public Material editorGhost;
        public Material editorSelection;
        public Material gizmoX;
        public Material gizmoY;
        public Material gizmoZ;
        public Material gizmoCenter;
        public Material gizmoHighlight;
        public Material triggerVolume;
        public Material line;
        public Material lineAdditive;
        public Material rope;
        public Material laser;
        public Material telegraph;
        public Material shield;
        public Material textMaterial;

        Dictionary<string, Material> lookup;
        Dictionary<string, Material> skyLookup;

        public static MaterialLibrary Instance => GameConfig.Instance != null ? GameConfig.Instance.materialLibrary : null;

        void OnEnable()
        {
            lookup = null;
            skyLookup = null;
        }

        public Material Get(string key)
        {
            if (string.IsNullOrEmpty(key)) return null;
            if (lookup == null) lookup = Build(materials);
            lookup.TryGetValue(key, out var mat);
            return mat;
        }

        public Material GetSkybox(string key)
        {
            if (string.IsNullOrEmpty(key)) return null;
            if (skyLookup == null) skyLookup = Build(skyboxes);
            skyLookup.TryGetValue(key, out var mat);
            return mat;
        }

        public void Set(string key, Material material)
        {
            var existing = materials.Find(e => e != null && string.Equals(e.key, key, StringComparison.OrdinalIgnoreCase));
            if (existing != null) existing.material = material;
            else materials.Add(new Entry { key = key, material = material });
            lookup = null;
        }

        public void SetSkybox(string key, Material material)
        {
            var existing = skyboxes.Find(e => e != null && string.Equals(e.key, key, StringComparison.OrdinalIgnoreCase));
            if (existing != null) existing.material = material;
            else skyboxes.Add(new Entry { key = key, material = material });
            skyLookup = null;
        }

        static Dictionary<string, Material> Build(List<Entry> entries)
        {
            var dict = new Dictionary<string, Material>(StringComparer.OrdinalIgnoreCase);
            foreach (var e in entries)
            {
                if (e != null && !string.IsNullOrEmpty(e.key) && e.material != null) dict[e.key] = e.material;
            }
            return dict;
        }

        /// <summary>Returns a material by key, or a fallback material (first entry) if missing.</summary>
        public static Material Resolve(string key)
        {
            var lib = Instance;
            if (lib == null) return null;
            var mat = lib.Get(key);
            if (mat == null) mat = lib.Get("White");
            return mat;
        }
    }
}
