using UnityEditor;
using UnityEngine;

namespace Momentum.EditorTools
{
    /// <summary>Saves the procedural meshes (ramp wedge, rings, cones, chevrons) as assets.</summary>
    public static class MeshAssetGenerator
    {
        public static Mesh Wedge { get; private set; }
        public static Mesh Torus { get; private set; }
        public static Mesh Cone { get; private set; }
        public static Mesh Band { get; private set; }
        public static Mesh Chevron { get; private set; }

        public static void Generate()
        {
            EditorUtil.EnsureFolder(GamePaths.Meshes);
            Wedge = Save(MeshGenerator.CreateWedge(), "Wedge");
            Torus = Save(MeshGenerator.CreateTorus(1f, 0.06f, 48, 8), "Torus");
            Cone = Save(MeshGenerator.CreateCone(0.5f, 1f, 24), "Cone");
            Band = Save(MeshGenerator.CreateBand(64, 0.05f), "Band");
            Chevron = Save(MeshGenerator.CreateChevron(), "Chevron");
        }

        static Mesh Save(Mesh mesh, string name)
        {
            mesh.name = name;
            return EditorUtil.SaveAsset(mesh, GamePaths.Meshes + "/" + name + ".asset");
        }

        /// <summary>Loads meshes generated by a previous run (used when only some generators run).</summary>
        public static void LoadExisting()
        {
            Wedge = AssetDatabase.LoadAssetAtPath<Mesh>(GamePaths.Meshes + "/Wedge.asset");
            Torus = AssetDatabase.LoadAssetAtPath<Mesh>(GamePaths.Meshes + "/Torus.asset");
            Cone = AssetDatabase.LoadAssetAtPath<Mesh>(GamePaths.Meshes + "/Cone.asset");
            Band = AssetDatabase.LoadAssetAtPath<Mesh>(GamePaths.Meshes + "/Band.asset");
            Chevron = AssetDatabase.LoadAssetAtPath<Mesh>(GamePaths.Meshes + "/Chevron.asset");
            if (Wedge == null || Torus == null || Cone == null || Band == null || Chevron == null) Generate();
        }
    }
}
